CMD_MANAGE=python manage.py
MEMCACHED_URL=memcached://127.0.0.1:11211/
IMAGES_PATH=/full/path/to/images/directory
FONTS_PATH=/full/path/to/fonts/directory
STYLE_PATH=/full/path/to/etconf/media/rst2pdf-stylesheet.style

DB_TYPE="postgresql" # Or "mysql"
DB_NAME="etegro"
DB_USER="username"
DB_PASSWORD="password"
DB_HOST="" # Leave empty if default
DB_PORT="" # Leave empty if default

DEBUG=yes
