CMD_MANAGE=python manage.py
MEMCACHED_URL=memcached://127.0.0.1:11211/
IMAGES_PATH=/var/www/etegro2/www/img
FONTS_PATH=/var/www/etegro2/fonts
STYLE_PATH=/var/www/etegro2/configurator/media/rst2pdf-stylesheet.style

# SQLite database related
SQLITE_DB_PATH=./configurator.db

# MySQL database related
MYSQL_NAME="etegro"
MYSQL_USER="etegro"
MYSQL_PASSWORD=""
MYSQL_HOST=""
MYSQL_PORT=""

DEBUG=yes
